# Generated by Django 4.0.6 on 2022-08-11 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whatsappdb',
            old_name='Contact',
            new_name='contact',
        ),
    ]
