# Generated by Django 4.0.6 on 2022-08-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_contact_whatsappdb_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappdb',
            name='photo',
            field=models.ImageField(default='', upload_to='polls/images'),
        ),
        migrations.AlterField(
            model_name='whatsappdb',
            name='contact',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='whatsappdb',
            name='pdf',
            field=models.FileField(upload_to='polls/docs'),
        ),
    ]
