# Generated by Django 4.0.6 on 2022-08-17 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_whatsappdb_photo_alter_whatsappdb_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappdb',
            name='pdf',
            field=models.FileField(upload_to='docs/'),
        ),
        migrations.AlterField(
            model_name='whatsappdb',
            name='photo',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
